### PR TITLE
Fix CryptoUtils not found

### PR DESCRIPTION
**Pull request by ScottPierce**
This fixes the bug I reported here: https://github.com/kaisellgren/mailer/issues/25

The https://pub.dartlang.org/packages/crypto library deprecated Base64 support prior to 1.0.0 and is pointing users to instead use the `dart:convert` library. This PR makes that change.

### CODE REVIEW

**Comment by spierce7** [comment]
Nevermind, it wasn't working because of my settings in gmail. I've sent and received an email successfully.

**Comment by fandegw** [comment]
+1

**Comment by Kleak** [comment]
+1

**Comment by danrubel** [comment]
Merged into https://github.com/kaisellgren/mailer/commit/9221b75ed26a098a0af4ac984c8364535a522b8a

**Comment by danrubel** [comment]
Thanks for the fix !

**Pull request closed without merging**
