### PR TITLE
adding a persistent connection

### PR DESCRIPTION
**Pull request by jodinathan**
added a new type of smtp client so we can persist the connection and send several messages faster

### CODE REVIEW

**Comment by jodinathan** [comment]
I've just extended SmtpClient and overridden the _send method.
So it has no change in the common use at all.

**Comment by close2** [comment]
Thanks for your PR!
Keeping the connection alive was one of my goals when rewriting the library.
(Notice that the `SmtpClient.send` function returns a `List` of `SendReport`s.)

I had troubles making sure that different `send` commands don't interleave.

Something like
```dart
List<Message> messages = someFunctionWhichGeneratesMessages();
Future.wait(messages.map(send));
```
should IMO work.

Also if one message fails, we should still be able to use the same connection.
This should be possible by starting every message with the smtp command: `RESET`.

IIRC there was also a problem with timeouts, but I am not sure any longer.

We should also be able to merge the `SmtpPersistentClient` into the `SmtpClient`.

My approach was to pass a List of messages, but I like how you simply call `send` multiple times.

If you are interested in rewriting your PR I will gladly add more detailed thoughts.

Otherwise I will try to find some time for implementing a persistent client in the next weeks.

**Comment by jodinathan** [comment]
I used the ```send multiple times``` approach because my need is not only send several messages at once, but rather wait for some info async and then send an email. 
Kind of this:

```
var cli = SmtpPersistentClient();

broker.listen((amqpMsg) async {
  // prepare the message using the info from the broker
  var msg = newMessage(html: amqpMsg.param['html']);
 // use the same connection to send
  cli.send(msg);
}, 
onDone: () => cli.close());
```

With the ```sendList()``` I could use a timer to not send one by one but a batch, which would probably be better. But even so, the connection could not be closed.

Is your idea like below?
 - Open connection
 - Send several
 - Close connection

**Comment by close2** [comment]
I am currently working on this in my development branch.

The default usage pattern for sending several mails using one connection will be something like:

* `new StmpClient(keepOpen: true)`
* `send(message)`
* 'send(anotherMessage)`...
* `close()`

The first `send` will then open the connection.

I might add an `open` call, in case you want to test if the smtp connection was successful.

**Comment by jodinathan** [comment]
I find a new class for Persistent client better than a flag.
It is pretty much like a database connection for me. 
- Connect
- Use
- Close

**Comment by jodinathan** [comment]
any news on this?

**Comment by close2** [comment]
Yes!
The new mailer version is ready for release.
https://github.com/close2/mailer/tree/dev

I am currently improving the documentation (mostly because of the xoauth2 authentication feature).

Shouldn't take more than a week.

**Pull request closed without merging**
